--mssv:20127392
--topic: 4_A
use QLDETAI
GO
--Q1--
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.PHAI=N'Nữ'

--Q2--
SELECT GV.HOTEN,GV.LUONG*1.1 AS LUONG_SAU
FROM GIAOVIEN GV

--Q3--
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV, BOMON BM
WHERE GV.HOTEN LIKE N'Nguyễn%' 
	AND GV.LUONG>2000 OR (GV.MAGV=BM.TRUONGBM AND YEAR(BM.NGAYNHANCHUC)>1995)

--Q4--
SELECT GV.HOTEN
FROM GIAOVIEN GV,BOMON BM
WHERE BM.MAKHOA='CNTT'
	AND BM.MABM=GV.MABM

--Q5--
SELECT *
FROM BOMON BM, GIAOVIEN GV
WHERE BM.TRUONGBM=GV.MAGV AND BM.TRUONGBM IS NOT NULL

--Q6--
SELECT GV.MAGV,GV.HOTEN, BM.MABM,BM.TENBM,BM.PHONG,BM.DIENTHOAI,BM.TRUONGBM,BM.MAKHOA,BM.NGAYNHANCHUC
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MABM=BM.MABM

--Q7--
SELECT DT.TENDT, GV.HOTEN
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV=DT.GVCNDT

--Q8--
SELECT K.TENKHOA,GV.*
FROM KHOA K,GIAOVIEN GV
WHERE K.TRUONGKHOA=GV.MAGV

--Q9--
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MABM IN (	SELECT BM.MABM
					FROM BOMON BM
					WHERE BM.TENBM=N'Vi sinh')

AND GV.MAGV IN (SELECT DT.GVCNDT
				FROM DETAI DT
				WHERE DT.MADT='006')

--Q10--
SELECT DT.MADT,CD.TENCD,DT.GVCNDT,GV.NGSINH,GV.DIACHI
FROM DETAI DT,CHUDE CD,GIAOVIEN GV
WHERE DT.CAPQL=N'Thành phố”'
	AND DT.MACD=CD.MACD AND DT.GVCNDT=GV.MAGV

--Q11--
SELECT GV.HOTEN,GV1.HOTEN AS HO_TEN_GVQLCM
FROM GIAOVIEN GV,GIAOVIEN GV1
WHERE GV.GVQLCM=GV1.MAGV
--Q12--
SELECT GV.HOTEN
FROM GIAOVIEN GV,GIAOVIEN GV1
WHERE GV1.HOTEN=N'Nguyễn Thanh Tùng'
	AND GV.GVQLCM=GV1.MAGV

--Q13--
SELECT GV.HOTEN
FROM GIAOVIEN GV,BOMON BM
WHERE GV.MAGV=BM.TRUONGBM AND BM.TENBM=N'Hệ thống thông tin'
--Q14--
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MAGV IN (	SELECT DT.GVCNDT
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD= CD.MACD AND CD.TENCD=N'Quản lý giáo dục')
--Q15--
SELECT CV.TENCV
FROM CONGVIEC CV
WHERE CV.MADT IN ( SELECT DT.MADT
					FROM DETAI DT
					WHERE DT.TENDT=N'HTTT quản lý các trường ĐH' 
						AND DT.NGAYBD>='2008-03-01' AND DT.NGAYBD<='2008-03-31')
--Q16--
SELECT GV.HOTEN,GV1.HOTEN AS HO_TEN_GVQLCM
FROM GIAOVIEN GV,GIAOVIEN GV1
WHERE GV.GVQLCM=GV1.MAGV
--Q17--
SELECT CV.*
FROM CONGVIEC CV
WHERE CV.NGAYBD>='2007-01-01' AND CV.NGAYBD <='2007-08-01'
--Q18--
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE GV1.MABM IN (SELECT BM.MABM
					FROM BOMON BM,GIAOVIEN GV
					WHERE GV.HOTEN=N'Trần Trà Hương'AND GV.MABM=GV1.MABM AND GV1.MAGV!=GV.MAGV)

--Q19--
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, BOMON BM, DETAI DT
WHERE GV.MAGV=BM.TRUONGBM AND GV.MAGV=DT.GVCNDT

--Q20--
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MAGV IN (SELECT K.TRUONGKHOA
					FROM KHOA K)
AND GV.MAGV IN (SELECT BM.TRUONGBM
				FROM BOMON BM)
--Q21--
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MAGV IN (SELECT BM.TRUONGBM
					FROM BOMON BM)

AND GV.MAGV IN (SELECT DT.GVCNDT
				FROM DETAI DT)

--Q22--
SELECT GV.MAGV
FROM GIAOVIEN GV
WHERE GV.MAGV IN (SELECT K.TRUONGKHOA
					FROM KHOA K)
AND GV.MAGV IN (SELECT DT.GVCNDT
				FROM DETAI DT)
--Q23--
SELECT GV.MAGV
FROM GIAOVIEN GV
WHERE GV.MABM IN(SELECT BM.MABM
				FROM BOMON BM
				WHERE BM.MABM='HTTT')
OR GV.MAGV IN(SELECT TG.MAGV
				FROM THAMGIADT TG
				WHERE TG.MADT='001')

--Q24--
SELECT DISTINCT GV2.*
FROM GIAOVIEN GV1, GIAOVIEN GV2,BOMON BM
WHERE GV1.MAGV='002' AND GV1.MABM=GV2.MABM AND GV1.MAGV!=GV2.MAGV

--Q25--
SELECT GV.*
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MAGV=BM.TRUONGBM

--Q26--
SELECT GV.HOTEN,GV.LUONG
FROM GIAOVIEN GV
