--mssv:20127392
--topic: 4_B
USE QLCHUYENBAY
GO
--Q17--
SELECT CB.SBDEN, COUNT(*) AS SOLUONG
FROM CHUYENBAY CB
GROUP BY CB.SBDEN
ORDER BY CB.SBDEN ASC

--Q18--
SELECT CB.SBDI,COUNT(*)AS SOLUONG
FROM CHUYENBAY CB
GROUP BY CB.SBDI
ORDER BY CB.SBDI ASC

--Q19--
SELECT CB.SBDI,LB.NGAYDI,COUNT(*)AS SOLUONG
FROM CHUYENBAY CB, LICHBAY LB
WHERE LB.MACB=CB.MACB
GROUP BY CB.SBDI,LB.NGAYDI

--Q20--
SELECT CB.SBDEN,LB.NGAYDI,COUNT(*) AS SOLUONG
FROM CHUYENBAY CB,LICHBAY LB
WHERE LB.MACB=CB.MACB
GROUP BY CB.SBDEN,LB.NGAYDI

--Q21--
SELECT LB.MACB,LB.NGAYDI,COUNT(*) AS SLNVKHONGLAPHICONG
FROM LICHBAY LB,NHANVIEN NV,PHANCONG PC
WHERE NV.MANV=PC.MANV AND PC.NGAYDI=LB.NGAYDI AND PC.MACB=LB.MACB AND NV.LOAINV=0
GROUP BY LB.MACB,LB.NGAYDI

--Q22--
SELECT CB.SBDI, LB.NGAYDI,COUNT(*) AS SLCHUYENBAY
FROM CHUYENBAY CB,LICHBAY LB
WHERE LB.MACB=CB.MACB AND CB.SBDI='MIA' AND LB.NGAYDI='2000-11-01'
GROUP BY CB.SBDI,LB.NGAYDI

--Q23--
SELECT LB.MACB,LB.NGAYDI,COUNT(*) AS SLNHANVIEN
FROM LICHBAY LB,NHANVIEN NV,PHANCONG PC
WHERE NV.MANV=PC.MANV AND LB.NGAYDI=PC.NGAYDI AND LB.MACB=PC.MACB 
GROUP BY LB.MACB,LB.NGAYDI
ORDER BY SLNHANVIEN DESC

--Q24--
SELECT LB.MACB,LB.NGAYDI,COUNT(*) AS SLKHDATCHO
FROM LICHBAY LB,DATCHO DC
WHERE LB.NGAYDI=DC.NGAYDI AND LB.MACB=DC.MACB
GROUP BY LB.MACB,LB.NGAYDI
ORDER BY SLKHDATCHO DESC

--Q25--
SELECT LB.MACB,LB.NGAYDI,SUM(NV.LUONG) AS TONG_LUONG
FROM LICHBAY LB, PHANCONG PC,NHANVIEN NV
WHERE PC.MANV=NV.MANV AND LB.NGAYDI=PC.NGAYDI AND LB.MACB=PC.MACB
GROUP BY LB.MACB,LB.NGAYDI
ORDER BY TONG_LUONG ASC

--Q26--
SELECT AVG(NV.LUONG) AS LUONG_TB
FROM NHANVIEN NV
WHERE NV.LOAINV=0

--Q27--
SELECT AVG(NV.LUONG) AS LUONG_TB_PC
FROM NHANVIEN NV
WHERE NV.LOAINV=1

--Q28--
SELECT LB.MALOAI,COUNT(*) AS SLCHUYENBAY
FROM LICHBAY LB,CHUYENBAY CB
WHERE CB.SBDEN='ORD'AND LB.MACB=CB.MACB
GROUP BY LB.MALOAI

--Q29--
SELECT CB.SBDI, COUNT(*) AS SLCHUYENBAY
FROM CHUYENBAY CB
WHERE CB.GIODI>='10:00:00' AND CB.GIODI<='22:00:00'
GROUP BY CB.SBDI
HAVING COUNT(*) >2

--Q30--
SELECT NV.TEN,PC.NGAYDI ,COUNT(*) AS SLCHUYENBAY
FROM NHANVIEN NV,PHANCONG PC
WHERE NV.MANV=PC.MANV AND NV.LOAINV=1
GROUP BY  NV.TEN,PC.NGAYDI
HAVING COUNT(*) >=2

--Q31--
SELECT LB.MACB,LB.NGAYDI,COUNT(*) AS SLDATCHO
FROM LICHBAY LB,DATCHO DC
WHERE DC.NGAYDI=LB.NGAYDI AND DC.MACB=LB.MACB
GROUP BY LB.MACB,LB.NGAYDI
HAVING COUNT(*)<3

--Q32--
SELECT LB.SOHIEU,LB.MALOAI,COUNT(*) AS SOLANPHANCONGLAI
FROM LICHBAY LB,PHANCONG PC,NHANVIEN NV
WHERE PC.MANV=NV.MANV AND PC.NGAYDI=LB.NGAYDI AND PC.MACB = LB.MACB
	AND NV.LOAINV=1 AND NV.MANV='1001'
GROUP BY LB.SOHIEU,LB.MALOAI
HAVING COUNT(*)>2

--Q33--
SELECT LMB.HANGSX,COUNT(*) AS SLLOAIMB
FROM LOAIMB LMB
GROUP BY LMB.HANGSX
