--mssv: 20127392
--topic: 5

USE QLCHUYENBAY
GO
--Q34--
SELECT LMB.HANGSX,LB.MALOAI,LB.SOHIEU
FROM LOAIMB LMB,LICHBAY LB
WHERE LB.MALOAI=LMB.MALOAI
GROUP BY LMB.HANGSX,LB.MALOAI,LB.SOHIEU
HAVING COUNT(LB.SOHIEU) >= ALL ( SELECT COUNT(LB1.SOHIEU)
					FROM LICHBAY LB1
					GROUP BY LB1.MALOAI,LB1.SOHIEU)

--Q35--
SELECT NV.TEN
FROM PHANCONG PC,NHANVIEN NV
WHERE NV.MANV=PC.MANV
GROUP BY NV.TEN,PC.MANV
HAVING COUNT(PC.MANV)>=ALL(SELECT COUNT(*)
							FROM PHANCONG PC1,NHANVIEN NV1
							WHERE PC1.MANV=NV1.MANV
							GROUP BY PC1.MANV )
--Q36--
SELECT NV.TEN,NV.DCHI,NV.DTHOAI
FROM NHANVIEN NV,PHANCONG PC
WHERE NV.LOAINV=1 AND PC.MANV=NV.MANV
GROUP BY NV.TEN,NV.DCHI,NV.DTHOAI,PC.MANV
HAVING COUNT(PC.MANV) >= ALL (SELECT COUNT(*)
							FROM PHANCONG PC1,NHANVIEN NV1
							WHERE PC1.MANV=NV1.MANV AND NV1.LOAINV=1
							GROUP BY PC1.MANV)
--Q37--
SELECT CB.SBDEN, COUNT(*) AS SLCHUYENBAYDAPITNHAT
FROM CHUYENBAY CB
GROUP BY CB.SBDEN
HAVING COUNT(*) <= ALL(SELECT COUNT(*)
						FROM CHUYENBAY CB1
						GROUP BY CB1.SBDEN)
--Q38--
SELECT CB.SBDI,COUNT(*) AS SLCHUYENBAYDINHIEUNHAT
FROM CHUYENBAY CB
GROUP BY CB.SBDI
HAVING COUNT(*) >= ALL (SELECT COUNT(*)
						FROM CHUYENBAY CB1
						GROUP BY CB1.SBDI)
--Q39--
SELECT KH.TEN,KH.DCHI,KH.DTHOAI
FROM KHACHHANG KH,DATCHO DC
WHERE DC.MAKH=KH.MAKH
GROUP BY DC.MAKH,KH.TEN,KH.DCHI,KH.DTHOAI
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
						FROM KHACHHANG KH1,DATCHO DC1
						WHERE DC1.MAKH=KH1.MAKH    
						GROUP BY DC1.MAKH )
--Q40--
SELECT NV.MANV,NV.TEN,NV.LUONG
FROM NHANVIEN NV ,KHANANG KN
WHERE NV.LOAINV=1 AND KN.MANV=NV.MANV
GROUP BY KN.MANV,NV.MANV,NV.TEN,NV.LUONG
HAVING COUNT(*) >= ALL (SELECT COUNT(*)
						FROM NHANVIEN NV1 ,KHANANG KN1
						WHERE NV1.LOAINV=1 AND KN1.MANV=NV1.MANV
						GROUP BY KN1.MANV)
--Q41--
SELECT NV.MANV,NV.TEN,NV.LUONG
FROM NHANVIEN NV
WHERE NV.LUONG >= ALL (SELECT NV1.LUONG
						FROM  NHANVIEN NV1)

--Q42--
SELECT NV.TEN,NV.DCHI
FROM NHANVIEN NV
WHERE NV.MANV IN (SELECT PC.MANV
				FROM PHANCONG PC,LICHBAY LB,NHANVIEN NV
				WHERE PC.NGAYDI=LB.NGAYDI AND PC.MACB=LB.MACB AND NV.MANV=PC.MANV )
AND NV.LUONG >= ALL ( SELECT NV1.LUONG
						FROM NHANVIEN NV1)

--Q43--
SELECT DISTINCT CB.MACB,CB.GIODI,CB.GIODEN
FROM CHUYENBAY CB ,LICHBAY LB
WHERE CB.MACB=LB.MACB
AND CB.GIODI <= ALL (SELECT CB1.GIODI
					FROM CHUYENBAY CB1,LICHBAY LB1 
					WHERE CB1.MACB=LB1.MACB)
--Q44--
SELECT CB.MACB,DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN)
FROM CHUYENBAY CB
WHERE DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) >=ALL (SELECT DATEDIFF(MINUTE,CB1.GIODI,CB1.GIODEN)
											FROM CHUYENBAY CB1)
--Q45--
SELECT CB.MACB,DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) AS THOIGIANBAY
FROM CHUYENBAY CB
WHERE DATEDIFF(MINUTE,CB.GIODI,CB.GIODEN) <=ALL (SELECT DATEDIFF(MINUTE,CB1.GIODI,CB1.GIODEN)
											FROM CHUYENBAY CB1)
--Q46--
SELECT LB.MACB,LB.NGAYDI
FROM LICHBAY LB
WHERE LB.MACB IN (SELECT LB2.MACB
				FROM LICHBAY LB2
				WHERE LB2.MALOAI='B747'
				GROUP BY LB2.MACB
				HAVING COUNT(LB2.MACB)>= ALL(SELECT COUNT(LB3.MACB) 
											FROM LICHBAY LB3
											WHERE LB3.MALOAI='B747'
											GROUP BY LB3.MACB))
--Q47--
SELECT LB.MACB,COUNT(DISTINCT PC.MANV) AS SLNHANVIEN
FROM DATCHO DC,LICHBAY LB,PHANCONG PC
WHERE LB.NGAYDI=PC.NGAYDI AND LB.MACB=PC.MACB AND DC.MACB=LB.MACB AND DC.NGAYDI=LB.NGAYDI
GROUP BY LB.MACB,LB.NGAYDI
HAVING COUNT(DISTINCT DC.MAKH)>3

--Q48--
SELECT NV.LOAINV,COUNT (*) AS SLNHANVIEN
FROM NHANVIEN NV
GROUP BY NV.LOAINV
HAVING  SUM(NV.LUONG)>600000

--Q49--
SELECT DC.MACB,COUNT(DISTINCT DC.MAKH)AS SLKHACHDATCHO
FROM DATCHO DC,LICHBAY LB,PHANCONG PC
WHERE DC.NGAYDI=LB.NGAYDI AND DC.MACB=LB.MACB AND PC.NGAYDI=LB.NGAYDI AND PC.MACB=LB.MACB
GROUP BY DC.MACB,DC.NGAYDI
HAVING COUNT(DISTINCT PC.MANV)>3

--Q50--
SELECT LB.MALOAI,COUNT(LB.MACB) AS SLCHUYENBAY
FROM LICHBAY LB
WHERE LB.MALOAI IN (SELECT MB.MALOAI
					FROM MAYBAY MB
					GROUP BY MB.MALOAI
					HAVING COUNT(*)>1)
GROUP BY LB.MALOAI
