USE QLCHUYENBAY
--Q1--
SELECT NV.MANV,NV.TEN,NV.DCHI,NV.DTHOAI
FROM NHANVIEN NV,KHANANG KN
WHERE NV.MANV=KN.MANV
	AND KN.MALOAI='B747'

--Q2--
SELECT CB.MACB,LB.NGAYDI
FROM CHUYENBAY CB, LICHBAY LB
WHERE CB.MACB=LB.MACB
	AND CB.SBDI='DCA'
	AND CB.GIODI >='14:00:00'
	AND CB.GIODEN<='18:00:00'

--Q3--
SELECT DISTINCT NV.TEN
FROM NHANVIEN NV,PHANCONG PC,CHUYENBAY CB
WHERE NV.MANV=PC.MANV
	AND PC.MACB='100'
	AND PC.MACB=CB.MACB
	AND CB.SBDI='SLC'

--Q4--
SELECT DISTINCT MB.SOHIEU, MB.MALOAI
FROM MAYBAY MB, CHUYENBAY CB, LICHBAY LB
WHERE LB.SOHIEU=MB.SOHIEU AND LB.MALOAI=MB.MALOAI
	AND LB.MACB=CB.MACB AND CB.SBDI='MIA'

--Q5--
SELECT LB.MACB,LB.NGAYDI, KH.TEN,KH.DCHI,KH.DTHOAI
FROM LICHBAY LB, KHACHHANG KH,DATCHO DC
WHERE DC.MACB=LB.MACB
	AND LB.NGAYDI=DC.NGAYDI
	AND DC.MAKH=KH.MAKH
ORDER BY LB.MACB ASC, LB.NGAYDI DESC

--Q6--
SELECT PC.MACB,PC.NGAYDI,NV.TEN,NV.DCHI,NV.DTHOAI
FROM PHANCONG PC, NHANVIEN NV
WHERE PC.MANV=NV.MANV
ORDER BY PC.MACB ASC, PC.NGAYDI DESC

--Q7--
SELECT PC.MACB,PC.NGAYDI,NV.MANV,NV.TEN
FROM PHANCONG PC,NHANVIEN NV,CHUYENBAY CB,LICHBAY LB
WHERE PC.MANV=NV.MANV
	AND PC.MACB=LB.MACB AND PC.NGAYDI=LB.NGAYDI
	AND LB.MACB=CB.MACB AND CB.SBDEN='ORD'

--Q8--
SELECT PC.MACB,PC.NGAYDI,NV.TEN
FROM PHANCONG PC,NHANVIEN NV
WHERE PC.MANV=NV.MANV
	AND NV.MANV='1001'

--Q9--
SELECT CB.MACB,CB.SBDI,CB.GIODI,CB.GIODEN,LB.NGAYDI
FROM CHUYENBAY CB, LICHBAY LB
WHERE LB.MACB=CB.MACB
	AND CB.SBDEN='DEN'
ORDER BY CB.SBDI ASC ,LB.NGAYDI DESC

--Q10--
SELECT NV.TEN,LMB.HANGSX,LMB.MALOAI
FROM LOAIMB LMB, KHANANG KN,NHANVIEN NV
WHERE KN.MANV=NV.MANV 
	AND KN.MALOAI=LMB.MALOAI 

--Q11--
SELECT NV.MANV,NV.TEN
FROM NHANVIEN NV,PHANCONG PC
WHERE PC.MANV=NV.MANV 
	AND PC.MACB='100' AND PC.NGAYDI='2000-01-11'

--Q12--
SELECT PC.MACB,PC.MANV,NV.TEN
FROM PHANCONG PC,NHANVIEN NV,LICHBAY LB,CHUYENBAY CB
WHERE PC.NGAYDI='2000-10-31'
	AND PC.NGAYDI=LB.NGAYDI AND LB.MACB=PC.MACB
	AND LB.MACB=CB.MACB AND CB.SBDI='MIA' AND CB.GIODI='20:30:00'
	AND PC.MANV=NV.MANV

--Q13--
SELECT PC.MACB,LB.SOHIEU,LB.MALOAI,LMB.HANGSX
FROM LICHBAY LB,NHANVIEN NV, PHANCONG PC,LOAIMB LMB,MAYBAY MB
WHERE NV.TEN='Quang' AND PC.MANV=NV.MANV
	AND PC.MACB=LB.MACB AND PC.NGAYDI=LB.NGAYDI
	AND LB.SOHIEU=MB.SOHIEU AND LB.MALOAI=MB.MALOAI
	AND MB.MALOAI=LMB.MALOAI

--Q14--
SELECT NV.TEN
FROM NHANVIEN NV
WHERE (MANV NOT IN (SELECT PC.MANV FROM PHANCONG PC))

--Q15--
SELECT DISTINCT TEN
FROM KHACHHANG KH, DATCHO DC,LICHBAY LB,MAYBAY MB,LOAIMB LMB
WHERE DC.MAKH=KH.MAKH AND DC.NGAYDI=LB.NGAYDI AND DC.MACB=LB.MACB
	AND LB.SOHIEU=MB.SOHIEU AND LB.MALOAI=MB.MALOAI
	AND MB.MALOAI=LMB.MALOAI AND LMB.HANGSX='Boeing'

--Q16--
SELECT LB.MACB
FROM LICHBAY LB,MAYBAY MB
WHERE MB.SOHIEU=10 AND MB.MALOAI='B747'
	AND LB.SOHIEU=MB.SOHIEU AND LB.MALOAI=MB.MALOAI
